//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace beastie
{
	public static class StringUtil
	{

	
		public static string JoinStrings(this IEnumerable<object> source, 
		                                         string separator)
		{
			StringBuilder builder = new StringBuilder();
			bool first = true;
			//foreach (T element in source)
			foreach (object element in source)
			{
				if (first)
				{
					first = false;
				}
				else
				{
					builder.Append(separator);
				}
				builder.Append(element);
			}
			return builder.ToString();
		}
		
	}


}

