//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace beastie.WordNet
{
	/// <summary>
	/// Database       : Sqlunet
	/// Data Source    : Sqlunet
	/// Server Version : 3.8.8.3
	/// </summary>
	public partial class SqlunetDB : LinqToDB.Data.DataConnection
	{
		public ITable<adjposition>               adjpositions              { get { return this.GetTable<adjposition>(); } }
		public ITable<adjpositiontype>           adjpositiontypes          { get { return this.GetTable<adjpositiontype>(); } }
		public ITable<bnc>                       bncs                      { get { return this.GetTable<bnc>(); } }
		public ITable<bncconvtask>               bncconvtasks              { get { return this.GetTable<bncconvtask>(); } }
		public ITable<bncimaginf>                bncimaginfs               { get { return this.GetTable<bncimaginf>(); } }
		public ITable<bncspwr>                   bncspwrs                  { get { return this.GetTable<bncspwr>(); } }
		public ITable<casedword>                 casedwords                { get { return this.GetTable<casedword>(); } }
		public ITable<fnannoset>                 fnannosets                { get { return this.GetTable<fnannoset>(); } }
		public ITable<fncoretype>                fncoretypes               { get { return this.GetTable<fncoretype>(); } }
		public ITable<fncorpus>                  fncorpuses                { get { return this.GetTable<fncorpus>(); } }
		public ITable<fncxn>                     fncxns                    { get { return this.GetTable<fncxn>(); } }
		public ITable<fndocument>                fndocuments               { get { return this.GetTable<fndocument>(); } }
		public ITable<fnfe>                      fnfes                     { get { return this.GetTable<fnfe>(); } }
		public ITable<fnfegrouprealization>      fnfegrouprealizations     { get { return this.GetTable<fnfegrouprealization>(); } }
		public ITable<fnfegrouprealizations_fes> fnfegrouprealizations_fes { get { return this.GetTable<fnfegrouprealizations_fes>(); } }
		public ITable<fnferealization>           fnferealizations          { get { return this.GetTable<fnferealization>(); } }
		public ITable<fnfes_excluded>            fnfes_excluded            { get { return this.GetTable<fnfes_excluded>(); } }
		public ITable<fnfes_required>            fnfes_required            { get { return this.GetTable<fnfes_required>(); } }
		public ITable<fnfes_semtypes>            fnfes_semtypes            { get { return this.GetTable<fnfes_semtypes>(); } }
		public ITable<fnfetype>                  fnfetypes                 { get { return this.GetTable<fnfetype>(); } }
		public ITable<fnframe>                   fnframes                  { get { return this.GetTable<fnframe>(); } }
		public ITable<fnframerelation>           fnframerelations          { get { return this.GetTable<fnframerelation>(); } }
		public ITable<fnframes_related>          fnframes_related          { get { return this.GetTable<fnframes_related>(); } }
		public ITable<fnframes_semtypes>         fnframes_semtypes         { get { return this.GetTable<fnframes_semtypes>(); } }
		public ITable<fngftype>                  fngftypes                 { get { return this.GetTable<fngftype>(); } }
		public ITable<fngovernor>                fngovernors               { get { return this.GetTable<fngovernor>(); } }
		public ITable<fngovernors_annosets>      fngovernors_annosets      { get { return this.GetTable<fngovernors_annosets>(); } }
		public ITable<fnlabel>                   fnlabels                  { get { return this.GetTable<fnlabel>(); } }
		public ITable<fnlabelitype>              fnlabelitypes             { get { return this.GetTable<fnlabelitype>(); } }
		public ITable<fnlabeltype>               fnlabeltypes              { get { return this.GetTable<fnlabeltype>(); } }
		public ITable<fnlayer>                   fnlayers                  { get { return this.GetTable<fnlayer>(); } }
		public ITable<fnlayertype>               fnlayertypes              { get { return this.GetTable<fnlayertype>(); } }
		public ITable<fnlexeme>                  fnlexemes                 { get { return this.GetTable<fnlexeme>(); } }
		public ITable<fnlexunit>                 fnlexunits                { get { return this.GetTable<fnlexunit>(); } }
		public ITable<fnlexunits_governors>      fnlexunits_governors      { get { return this.GetTable<fnlexunits_governors>(); } }
		public ITable<fnlexunits_semtypes>       fnlexunits_semtypes       { get { return this.GetTable<fnlexunits_semtypes>(); } }
		public ITable<fnpattern>                 fnpatterns                { get { return this.GetTable<fnpattern>(); } }
		public ITable<fnpatterns_annosets>       fnpatterns_annosets       { get { return this.GetTable<fnpatterns_annosets>(); } }
		public ITable<fnpatterns_valenceunits>   fnpatterns_valenceunits   { get { return this.GetTable<fnpatterns_valenceunits>(); } }
		public ITable<fnpos>                     fnposes                   { get { return this.GetTable<fnpos>(); } }
		public ITable<fnpttype>                  fnpttypes                 { get { return this.GetTable<fnpttype>(); } }
		public ITable<fnsemtype>                 fnsemtypes                { get { return this.GetTable<fnsemtype>(); } }
		public ITable<fnsemtypes_supers>         fnsemtypes_supers         { get { return this.GetTable<fnsemtypes_supers>(); } }
		public ITable<fnsentence>                fnsentences               { get { return this.GetTable<fnsentence>(); } }
		public ITable<fnstatus>                  fnstatuses                { get { return this.GetTable<fnstatus>(); } }
		public ITable<fnsubcorpus>               fnsubcorpuses             { get { return this.GetTable<fnsubcorpus>(); } }
		public ITable<fnsubcorpuses_sentences>   fnsubcorpuses_sentences   { get { return this.GetTable<fnsubcorpuses_sentences>(); } }
		public ITable<fnvalenceunit>             fnvalenceunits            { get { return this.GetTable<fnvalenceunit>(); } }
		public ITable<fnvalenceunits_annosets>   fnvalenceunits_annosets   { get { return this.GetTable<fnvalenceunits_annosets>(); } }
		public ITable<fnword>                    fnwords                   { get { return this.GetTable<fnword>(); } }
		public ITable<glf>                       glfs                      { get { return this.GetTable<glf>(); } }
		public ITable<ilf>                       ilfs                      { get { return this.GetTable<ilf>(); } }
		public ITable<lexdomain>                 lexdomains                { get { return this.GetTable<lexdomain>(); } }
		public ITable<lexlink>                   lexlinks                  { get { return this.GetTable<lexlink>(); } }
		public ITable<linktype>                  linktypes                 { get { return this.GetTable<linktype>(); } }
		public ITable<log>                       logs                      { get { return this.GetTable<log>(); } }
		public ITable<morph>                     morphs                    { get { return this.GetTable<morph>(); } }
		public ITable<morphmap>                  morphmaps                 { get { return this.GetTable<morphmap>(); } }
		public ITable<pbarg>                     pbargs                    { get { return this.GetTable<pbarg>(); } }
		public ITable<pbargn>                    pbargns                   { get { return this.GetTable<pbargn>(); } }
		public ITable<pbaspect>                  pbaspects                 { get { return this.GetTable<pbaspect>(); } }
		public ITable<pbexample>                 pbexamples                { get { return this.GetTable<pbexample>(); } }
		public ITable<pbform>                    pbforms                   { get { return this.GetTable<pbform>(); } }
		public ITable<pbfunc>                    pbfuncs                   { get { return this.GetTable<pbfunc>(); } }
		public ITable<pbperson>                  pbpersons                 { get { return this.GetTable<pbperson>(); } }
		public ITable<pbrel>                     pbrels                    { get { return this.GetTable<pbrel>(); } }
		public ITable<pbrole>                    pbroles                   { get { return this.GetTable<pbrole>(); } }
		public ITable<pbroleset>                 pbrolesets                { get { return this.GetTable<pbroleset>(); } }
		public ITable<pbtens>                    pbtenses                  { get { return this.GetTable<pbtens>(); } }
		public ITable<pbvnmap>                   pbvnmaps                  { get { return this.GetTable<pbvnmap>(); } }
		public ITable<pbvntheta>                 pbvnthetas                { get { return this.GetTable<pbvntheta>(); } }
		public ITable<pbvoice>                   pbvoices                  { get { return this.GetTable<pbvoice>(); } }
		public ITable<pbword>                    pbwords                   { get { return this.GetTable<pbword>(); } }
		public ITable<postype>                   postypes                  { get { return this.GetTable<postype>(); } }
		public ITable<predicatematrix>           predicatematrices         { get { return this.GetTable<predicatematrix>(); } }
		public ITable<sample>                    samples                   { get { return this.GetTable<sample>(); } }
		public ITable<semlink>                   semlinks                  { get { return this.GetTable<semlink>(); } }
		public ITable<sens>                      senses                    { get { return this.GetTable<sens>(); } }
		public ITable<sensemaps2021>             sensemaps2021             { get { return this.GetTable<sensemaps2021>(); } }
		public ITable<sensemaps2130>             sensemaps2130             { get { return this.GetTable<sensemaps2130>(); } }
		public ITable<sensemaps3031>             sensemaps3031             { get { return this.GetTable<sensemaps3031>(); } }
		public ITable<senses20>                  senses20                  { get { return this.GetTable<senses20>(); } }
		public ITable<senses21>                  senses21                  { get { return this.GetTable<senses21>(); } }
		public ITable<senses30>                  senses30                  { get { return this.GetTable<senses30>(); } }
		public ITable<sumofile>                  sumofiles                 { get { return this.GetTable<sumofile>(); } }
		public ITable<sumoformula>               sumoformulas              { get { return this.GetTable<sumoformula>(); } }
		public ITable<sumomap>                   sumomaps                  { get { return this.GetTable<sumomap>(); } }
		public ITable<sumoparsemap>              sumoparsemaps             { get { return this.GetTable<sumoparsemap>(); } }
		public ITable<sumoterm>                  sumoterms                 { get { return this.GetTable<sumoterm>(); } }
		public ITable<sumotermattr>              sumotermattrs             { get { return this.GetTable<sumotermattr>(); } }
		public ITable<synset>                    synsets                   { get { return this.GetTable<synset>(); } }
		public ITable<synsetmaps2031>            synsetmaps2031            { get { return this.GetTable<synsetmaps2031>(); } }
		public ITable<synsetmaps2131>            synsetmaps2131            { get { return this.GetTable<synsetmaps2131>(); } }
		public ITable<synsetmaps3031>            synsetmaps3031            { get { return this.GetTable<synsetmaps3031>(); } }
		public ITable<vframe>                    vframes                   { get { return this.GetTable<vframe>(); } }
		public ITable<vframemap>                 vframemaps                { get { return this.GetTable<vframemap>(); } }
		public ITable<vframesentence>            vframesentences           { get { return this.GetTable<vframesentence>(); } }
		public ITable<vframesentencemap>         vframesentencemaps        { get { return this.GetTable<vframesentencemap>(); } }
		public ITable<vnclass>                   vnclasses                 { get { return this.GetTable<vnclass>(); } }
		public ITable<vnclassmember>             vnclassmembers            { get { return this.GetTable<vnclassmember>(); } }
		public ITable<vnclassmembersens>         vnclassmembersenses       { get { return this.GetTable<vnclassmembersens>(); } }
		public ITable<vnexample>                 vnexamples                { get { return this.GetTable<vnexample>(); } }
		public ITable<vnexamplemap>              vnexamplemaps             { get { return this.GetTable<vnexamplemap>(); } }
		public ITable<vnframe>                   vnframes                  { get { return this.GetTable<vnframe>(); } }
		public ITable<vnframemap>                vnframemaps               { get { return this.GetTable<vnframemap>(); } }
		public ITable<vnframename>               vnframenames              { get { return this.GetTable<vnframename>(); } }
		public ITable<vnframesubname>            vnframesubnames           { get { return this.GetTable<vnframesubname>(); } }
		public ITable<vngrouping>                vngroupings               { get { return this.GetTable<vngrouping>(); } }
		public ITable<vngroupingmap>             vngroupingmaps            { get { return this.GetTable<vngroupingmap>(); } }
		public ITable<vnpredicate>               vnpredicates              { get { return this.GetTable<vnpredicate>(); } }
		public ITable<vnpredicatemap>            vnpredicatemaps           { get { return this.GetTable<vnpredicatemap>(); } }
		public ITable<vnrestr>                   vnrestrs                  { get { return this.GetTable<vnrestr>(); } }
		public ITable<vnrestrtype>               vnrestrtypes              { get { return this.GetTable<vnrestrtype>(); } }
		public ITable<vnrole>                    vnroles                   { get { return this.GetTable<vnrole>(); } }
		public ITable<vnrolemap>                 vnrolemaps                { get { return this.GetTable<vnrolemap>(); } }
		public ITable<vnroletype>                vnroletypes               { get { return this.GetTable<vnroletype>(); } }
		public ITable<vnsemantic>                vnsemantics               { get { return this.GetTable<vnsemantic>(); } }
		public ITable<vnsyntax>                  vnsyntaxes                { get { return this.GetTable<vnsyntax>(); } }
		public ITable<vnword>                    vnwords                   { get { return this.GetTable<vnword>(); } }
		public ITable<word>                      words                     { get { return this.GetTable<word>(); } }
		public ITable<xwnparselft>               xwnparselfts              { get { return this.GetTable<xwnparselft>(); } }
		public ITable<xwnwsd>                    xwnwsds                   { get { return this.GetTable<xwnwsd>(); } }

		public SqlunetDB()
		{
			InitDataContext();
		}

		public SqlunetDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("adjpositions")]
	public partial class adjposition
	{
		[PrimaryKey(0), NotNull] public long   synsetid { get; set; } // integer
		[PrimaryKey(1), NotNull] public long   wordid   { get; set; } // integer
		[Column,        NotNull] public object position { get; set; } // character
	}

	[Table("adjpositiontypes")]
	public partial class adjpositiontype
	{
		[PrimaryKey, NotNull] public object position     { get; set; } // character 
		[Column,     NotNull] public object positionname { get; set; } // varchar
	}

	[Table("bncs")]
	public partial class bnc
	{
		[PrimaryKey(0), NotNull    ] public long    wordid { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public object  pos    { get; set; } // character 
		[Column,           Nullable] public long?   freq   { get; set; } // integer
		[Column,           Nullable] public long?   range  { get; set; } // integer
		[Column,           Nullable] public double? disp   { get; set; } // float
	}

	[Table("bncconvtasks")]
	public partial class bncconvtask
	{
		[PrimaryKey(0), NotNull    ] public long    wordid { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public object  pos    { get; set; } // character 
		[Column,           Nullable] public long?   freq1  { get; set; } // integer
		[Column,           Nullable] public long?   range1 { get; set; } // integer
		[Column,           Nullable] public double? disp1  { get; set; } // float
		[Column,           Nullable] public long?   freq2  { get; set; } // integer
		[Column,           Nullable] public long?   range2 { get; set; } // integer
		[Column,           Nullable] public double? disp2  { get; set; } // float
		[Column,           Nullable] public double? ll     { get; set; } // float
	}

	[Table("bncimaginfs")]
	public partial class bncimaginf
	{
		[PrimaryKey(0), NotNull    ] public long    wordid { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public object  pos    { get; set; } // character 
		[Column,           Nullable] public long?   freq1  { get; set; } // integer
		[Column,           Nullable] public long?   range1 { get; set; } // integer
		[Column,           Nullable] public double? disp1  { get; set; } // float
		[Column,           Nullable] public long?   freq2  { get; set; } // integer
		[Column,           Nullable] public long?   range2 { get; set; } // integer
		[Column,           Nullable] public double? disp2  { get; set; } // float
		[Column,           Nullable] public double? ll     { get; set; } // float
	}

	[Table("bncspwrs")]
	public partial class bncspwr
	{
		[PrimaryKey(0), NotNull    ] public long    wordid { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public object  pos    { get; set; } // character 
		[Column,           Nullable] public long?   freq1  { get; set; } // integer
		[Column,           Nullable] public long?   range1 { get; set; } // integer
		[Column,           Nullable] public double? disp1  { get; set; } // float
		[Column,           Nullable] public long?   freq2  { get; set; } // integer
		[Column,           Nullable] public long?   range2 { get; set; } // integer
		[Column,           Nullable] public double? disp2  { get; set; } // float
		[Column,           Nullable] public double? ll     { get; set; } // float
	}

	[Table("casedwords")]
	public partial class casedword
	{
		[PrimaryKey, NotNull] public long   casedwordid { get; set; } // integer
		[Column,     NotNull] public long   wordid      { get; set; } // integer
		[Column,     NotNull] public object cased       { get; set; } // varchar
	}

	[Table("fnannosets")]
	public partial class fnannoset
	{
		[PrimaryKey, NotNull    ] public long   annosetid  { get; set; } // integer
		[Column,     NotNull    ] public long   sentenceid { get; set; } // integer
		[Column,        Nullable] public long?  frameid    { get; set; } // integer
		[Column,        Nullable] public long?  luid       { get; set; } // integer
		[Column,        Nullable] public long?  cxnid      { get; set; } // integer
		[Column,        Nullable] public long?  statusid   { get; set; } // integer
		[Column,        Nullable] public string cdate      { get; set; } // varchar(27)
		[Column,        Nullable] public long?  noccurs    { get; set; } // integer
	}

	[Table("fncoretypes")]
	public partial class fncoretype
	{
		[PrimaryKey, Identity] public long   coretypeid { get; set; } // integer
		[Column,     Nullable] public string coretype   { get; set; } // varchar(16)
	}

	[Table("fncorpuses")]
	public partial class fncorpus
	{
		[PrimaryKey, NotNull    ] public long   corpusid { get; set; } // integer
		[Column,        Nullable] public string corpus   { get; set; } // varchar(80)
		[Column,        Nullable] public long?  luid     { get; set; } // integer
		[Column,        Nullable] public long?  noccurs  { get; set; } // integer
	}

	[Table("fncxns")]
	public partial class fncxn
	{
		[PrimaryKey, NotNull    ] public long   cxnid { get; set; } // integer
		[Column,        Nullable] public string cxn   { get; set; } // varchar(32)
	}

	[Table("fndocuments")]
	public partial class fndocument
	{
		[PrimaryKey, NotNull    ] public long   documentid   { get; set; } // integer
		[Column,        Nullable] public long?  corpusid     { get; set; } // integer
		[Column,        Nullable] public string documentdesc { get; set; } // varchar(64)
		[Column,        Nullable] public long?  noccurs      { get; set; } // integer
	}

	[Table("fnfes")]
	public partial class fnfe
	{
		[PrimaryKey, NotNull    ] public long   feid         { get; set; } // integer
		[Column,        Nullable] public long?  frameid      { get; set; } // integer
		[Column,        Nullable] public long?  fetypeid     { get; set; } // integer
		[Column,        Nullable] public string feabbrev     { get; set; } // varchar(24)
		[Column,        Nullable] public string fedefinition { get; set; } // text(max)
		[Column,        Nullable] public long?  coretypeid   { get; set; } // integer
		[Column,        Nullable] public long?  coreset      { get; set; } // integer
		[Column,        Nullable] public string fgcolor      { get; set; } // varchar(6)
		[Column,        Nullable] public string bgcolor      { get; set; } // varchar(6)
		[Column,        Nullable] public string cdate        { get; set; } // varchar(27)
		[Column,        Nullable] public string cby          { get; set; } // varchar(5)
	}

	[Table("fnfegrouprealizations")]
	public partial class fnfegrouprealization
	{
		[PrimaryKey, NotNull    ] public long  fegrid { get; set; } // integer
		[Column,        Nullable] public long? luid   { get; set; } // integer
		[Column,        Nullable] public long? total  { get; set; } // integer
	}

	[Table("fnfegrouprealizations_fes")]
	public partial class fnfegrouprealizations_fes
	{
		[PrimaryKey, NotNull    ] public long  rfeid    { get; set; } // integer
		[Column,     NotNull    ] public long  fegrid   { get; set; } // integer
		[Column,        Nullable] public long? feid     { get; set; } // integer
		[Column,        Nullable] public long? fetypeid { get; set; } // integer
	}

	[Table("fnferealizations")]
	public partial class fnferealization
	{
		[PrimaryKey, NotNull    ] public long  ferid    { get; set; } // integer
		[Column,        Nullable] public long? luid     { get; set; } // integer
		[Column,        Nullable] public long? fetypeid { get; set; } // integer
		[Column,        Nullable] public long? feid     { get; set; } // integer
		[Column,        Nullable] public long? total    { get; set; } // integer
	}

	[Table("fnfes_excluded")]
	public partial class fnfes_excluded
	{
		[PrimaryKey(0), NotNull] public long feid  { get; set; } // integer
		[PrimaryKey(1), NotNull] public long fe2id { get; set; } // integer
	}

	[Table("fnfes_required")]
	public partial class fnfes_required
	{
		[PrimaryKey(0), NotNull] public long feid  { get; set; } // integer
		[PrimaryKey(1), NotNull] public long fe2id { get; set; } // integer
	}

	[Table("fnfes_semtypes")]
	public partial class fnfes_semtypes
	{
		[PrimaryKey(0), NotNull] public long feid      { get; set; } // integer
		[PrimaryKey(1), NotNull] public long semtypeid { get; set; } // integer
	}

	[Table("fnfetypes")]
	public partial class fnfetype
	{
		[PrimaryKey, Identity] public long   fetypeid { get; set; } // integer
		[Column,     Nullable] public string fetype   { get; set; } // varchar(30)
	}

	[Table("fnframes")]
	public partial class fnframe
	{
		[PrimaryKey, NotNull    ] public long   frameid         { get; set; } // integer
		[Column,        Nullable] public string frame           { get; set; } // varchar(40)
		[Column,        Nullable] public string framedefinition { get; set; } // text(max)
		[Column,        Nullable] public string cdate           { get; set; } // varchar(27)
		[Column,        Nullable] public string cby             { get; set; } // varchar(5)
	}

	[Table("fnframerelations")]
	public partial class fnframerelation
	{
		[PrimaryKey, Identity] public long   relationid { get; set; } // integer
		[Column,     Nullable] public string relation   { get; set; } // varchar(20)
	}

	[Table("fnframes_related")]
	public partial class fnframes_related
	{
		[Column, NotNull    ] public long  frameid    { get; set; } // integer
		[Column,    Nullable] public long? frame2id   { get; set; } // integer
		[Column,    Nullable] public long? relationid { get; set; } // integer
	}

	[Table("fnframes_semtypes")]
	public partial class fnframes_semtypes
	{
		[PrimaryKey(0), NotNull] public long frameid   { get; set; } // integer
		[PrimaryKey(1), NotNull] public long semtypeid { get; set; } // integer
	}

	[Table("fngftypes")]
	public partial class fngftype
	{
		[PrimaryKey, Identity] public long   gfid { get; set; } // integer
		[Column,     Nullable] public string gf   { get; set; } // varchar(10)
	}

	[Table("fngovernors")]
	public partial class fngovernor
	{
		[PrimaryKey, NotNull    ] public long   governorid   { get; set; } // integer
		[Column,        Nullable] public long?  fnwordid     { get; set; } // integer
		[Column,        Nullable] public string governortype { get; set; } // varchar(5)
	}

	[Table("fngovernors_annosets")]
	public partial class fngovernors_annosets
	{
		[PrimaryKey(0), NotNull] public long governorid { get; set; } // integer
		[PrimaryKey(1), NotNull] public long annosetid  { get; set; } // integer
	}

	[Table("fnlabels")]
	public partial class fnlabel
	{
		[PrimaryKey, NotNull    ] public long   labelid      { get; set; } // integer
		[Column,        Nullable] public long?  layerid      { get; set; } // integer
		[Column,        Nullable] public long?  labeltypeid  { get; set; } // integer
		[Column,        Nullable] public long?  labelitypeid { get; set; } // integer
		[Column,        Nullable] public long?  feid         { get; set; } // integer
		[Column,        Nullable] public long?  start        { get; set; } // integer
		[Column,        Nullable] public long?  end          { get; set; } // integer
		[Column,        Nullable] public string fgcolor      { get; set; } // varchar(6)
		[Column,        Nullable] public string bgcolor      { get; set; } // varchar(6)
		[Column,        Nullable] public string cby          { get; set; } // varchar(27)
	}

	[Table("fnlabelitypes")]
	public partial class fnlabelitype
	{
		[PrimaryKey, Identity] public long   labelitypeid    { get; set; } // integer
		[Column,     Nullable] public string labelitype      { get; set; } // varchar(4)
		[Column,     Nullable] public string labelitypedescr { get; set; } // varchar(16)
	}

	[Table("fnlabeltypes")]
	public partial class fnlabeltype
	{
		[PrimaryKey, Identity] public long   labeltypeid { get; set; } // integer
		[Column,     Nullable] public string labeltype   { get; set; } // varchar(26)
	}

	[Table("fnlayers")]
	public partial class fnlayer
	{
		[PrimaryKey, NotNull    ] public long  layerid     { get; set; } // integer
		[Column,     NotNull    ] public long  annosetid   { get; set; } // integer
		[Column,        Nullable] public long? layertypeid { get; set; } // integer
		[Column,        Nullable] public long? rank        { get; set; } // integer
	}

	[Table("fnlayertypes")]
	public partial class fnlayertype
	{
		[PrimaryKey, Identity] public long   layertypeid { get; set; } // integer
		[Column,     Nullable] public string layertype   { get; set; } // varchar(6)
	}

	[Table("fnlexemes")]
	public partial class fnlexeme
	{
		[PrimaryKey, NotNull    ] public long  lexemeid    { get; set; } // integer
		[Column,        Nullable] public long? luid        { get; set; } // integer
		[Column,        Nullable] public long? fnwordid    { get; set; } // integer
		[Column,        Nullable] public long? posid       { get; set; } // integer
		[Column,        Nullable] public bool? breakbefore { get; set; } // boolean
		[Column,        Nullable] public bool? headword    { get; set; } // boolean
		[Column,        Nullable] public long? lexemeidx   { get; set; } // integer
	}

	[Table("fnlexunits")]
	public partial class fnlexunit
	{
		[PrimaryKey, NotNull    ] public long   luid                 { get; set; } // integer
		[Column,        Nullable] public long?  frameid              { get; set; } // integer
		[Column,        Nullable] public string lexunit              { get; set; } // varchar(64)
		[Column,        Nullable] public long?  posid                { get; set; } // integer
		[Column,        Nullable] public string ludefinition         { get; set; } // text(max)
		[Column,        Nullable] public object ludict               { get; set; } // character
		[Column,        Nullable] public long?  statusid             { get; set; } // integer
		[Column,        Nullable] public long?  totalannotated       { get; set; } // integer
		[Column,        Nullable] public long?  incorporatedfeid     { get; set; } // integer
		[Column,        Nullable] public long?  incorporatedfetypeid { get; set; } // integer
		[Column,        Nullable] public long?  noccurs              { get; set; } // integer
	}

	[Table("fnlexunits_governors")]
	public partial class fnlexunits_governors
	{
		[PrimaryKey(0), NotNull] public long luid       { get; set; } // integer
		[PrimaryKey(1), NotNull] public long governorid { get; set; } // integer
	}

	[Table("fnlexunits_semtypes")]
	public partial class fnlexunits_semtypes
	{
		[PrimaryKey(0), NotNull] public long luid      { get; set; } // integer
		[PrimaryKey(1), NotNull] public long semtypeid { get; set; } // integer
	}

	[Table("fnpatterns")]
	public partial class fnpattern
	{
		[PrimaryKey, NotNull    ] public long  patternid { get; set; } // integer
		[Column,        Nullable] public long? fegrid    { get; set; } // integer
		[Column,        Nullable] public long? total     { get; set; } // integer
	}

	[Table("fnpatterns_annosets")]
	public partial class fnpatterns_annosets
	{
		[PrimaryKey(0), NotNull] public long patternid { get; set; } // integer
		[PrimaryKey(1), NotNull] public long annosetid { get; set; } // integer
	}

	[Table("fnpatterns_valenceunits")]
	public partial class fnpatterns_valenceunits
	{
		[PrimaryKey, Identity   ] public long  pvid      { get; set; } // integer
		[Column,     NotNull    ] public long  patternid { get; set; } // integer
		[Column,     NotNull    ] public long  vuid      { get; set; } // integer
		[Column,        Nullable] public long? feid      { get; set; } // integer
		[Column,        Nullable] public long? fetypeid  { get; set; } // integer
	}

	[Table("fnposes")]
	public partial class fnpos
	{
		[PrimaryKey, Identity] public long   posid { get; set; } // integer
		[Column,     Nullable] public string pos   { get; set; } // varchar(8)
	}

	[Table("fnpttypes")]
	public partial class fnpttype
	{
		[PrimaryKey, Identity] public long   ptid { get; set; } // integer
		[Column,     Nullable] public string pt   { get; set; } // varchar(20)
	}

	[Table("fnsemtypes")]
	public partial class fnsemtype
	{
		[PrimaryKey, NotNull    ] public long   semtypeid         { get; set; } // integer
		[Column,        Nullable] public string semtype           { get; set; } // varchar(32)
		[Column,        Nullable] public string semtypeabbrev     { get; set; } // varchar(24)
		[Column,        Nullable] public string semtypedefinition { get; set; } // text(max)
	}

	[Table("fnsemtypes_supers")]
	public partial class fnsemtypes_supers
	{
		[PrimaryKey(0), NotNull] public long semtypeid      { get; set; } // integer
		[PrimaryKey(1), NotNull] public long supersemtypeid { get; set; } // integer
	}

	[Table("fnsentences")]
	public partial class fnsentence
	{
		[PrimaryKey, NotNull    ] public long   sentenceid { get; set; } // integer
		[Column,        Nullable] public long?  documentid { get; set; } // integer
		[Column,        Nullable] public long?  corpusid   { get; set; } // integer
		[Column,        Nullable] public long?  paragno    { get; set; } // integer
		[Column,        Nullable] public long?  sentno     { get; set; } // integer
		[Column,        Nullable] public string text       { get; set; } // text(max)
		[Column,        Nullable] public long?  apos       { get; set; } // integer
		[Column,        Nullable] public long?  noccurs    { get; set; } // integer
	}

	[Table("fnstatuses")]
	public partial class fnstatus
	{
		[PrimaryKey, NotNull    ] public long   statusid { get; set; } // integer
		[Column,        Nullable] public string status   { get; set; } // varchar(32)
	}

	[Table("fnsubcorpuses")]
	public partial class fnsubcorpus
	{
		[PrimaryKey, NotNull    ] public long   subcorpusid { get; set; } // integer
		[Column,        Nullable] public long?  luid        { get; set; } // integer
		[Column,        Nullable] public string subcorpus   { get; set; } // varchar(80)
	}

	[Table("fnsubcorpuses_sentences")]
	public partial class fnsubcorpuses_sentences
	{
		[PrimaryKey(0), NotNull] public long subcorpusid { get; set; } // integer
		[PrimaryKey(1), NotNull] public long sentenceid  { get; set; } // integer
	}

	[Table("fnvalenceunits")]
	public partial class fnvalenceunit
	{
		[PrimaryKey, NotNull    ] public long  vuid  { get; set; } // integer
		[Column,     NotNull    ] public long  ferid { get; set; } // integer
		[Column,        Nullable] public long? ptid  { get; set; } // integer
		[Column,        Nullable] public long? gfid  { get; set; } // integer
	}

	[Table("fnvalenceunits_annosets")]
	public partial class fnvalenceunits_annosets
	{
		[PrimaryKey(0), NotNull] public long vuid      { get; set; } // integer
		[PrimaryKey(1), NotNull] public long annosetid { get; set; } // integer
	}

	[Table("fnwords")]
	public partial class fnword
	{
		[PrimaryKey, NotNull    ] public long   fnwordid { get; set; } // integer
		[Column,        Nullable] public long?  wordid   { get; set; } // integer
		[Column,        Nullable] public string word     { get; set; } // varchar(30)
	}

	[Table("glfs")]
	public partial class glf
	{
		[Column, NotNull    ] public long   wordid   { get; set; } // integer
		[Column, NotNull    ] public long   synsetid { get; set; } // integer
		[Column, NotNull    ] public string lf       { get; set; } // text(max)
		[Column,    Nullable] public string text     { get; set; } // text(max)
		[Column, NotNull    ] public bool   issub    { get; set; } // boolean
	}

	[Table("ilfs")]
	public partial class ilf
	{
		[Column, NotNull    ] public long   wordid   { get; set; } // integer
		[Column, NotNull    ] public long   synsetid { get; set; } // integer
		[Column, NotNull    ] public string lf       { get; set; } // text(max)
		[Column, NotNull    ] public string prettylf { get; set; } // text(max)
		[Column,    Nullable] public string text     { get; set; } // text(max)
	}

	[Table("lexdomains")]
	public partial class lexdomain
	{
		[Column(),            PrimaryKey,  NotNull] public long   lexdomainid      { get; set; } // integer
		[Column(),               Nullable         ] public object lexdomainname    { get; set; } // varchar 
		[Column("lexdomain"),    Nullable         ] public object lexdomain_Column { get; set; } // varchar 
		[Column(),               Nullable         ] public object pos              { get; set; } // character
	}

	[Table("lexlinks")]
	public partial class lexlink
	{
		[PrimaryKey(1), NotNull] public long synset1id { get; set; } // integer
		[PrimaryKey(0), NotNull] public long word1id   { get; set; } // integer
		[PrimaryKey(3), NotNull] public long synset2id { get; set; } // integer
		[PrimaryKey(2), NotNull] public long word2id   { get; set; } // integer
		[PrimaryKey(4), NotNull] public long linkid    { get; set; } // integer
	}

	[Table("linktypes")]
	public partial class linktype
	{
		[PrimaryKey, NotNull    ] public long   linkid   { get; set; } // integer
		[Column,        Nullable] public object link     { get; set; } // varchar 
		[Column,     NotNull    ] public bool   recurses { get; set; } // boolean
	}

	[Table("logs")]
	public partial class log
	{
		[Column(),         PrimaryKey,  Identity] public long   id       { get; set; } // integer
		[Column(),         NotNull              ] public object module   { get; set; } // varchar 
		[Column(),         NotNull              ] public object tag      { get; set; } // varchar 
		[Column(),         NotNull              ] public object subtag   { get; set; } // varchar 
		[Column(),            Nullable          ] public object source   { get; set; } // varchar 
		[Column(),            Nullable          ] public long?  location { get; set; } // integer
		[Column("object"), NotNull              ] public string @object  { get; set; } // text(max)
		[Column(),            Nullable          ] public string exc      { get; set; } // text(max)
	}

	[Table("morphs")]
	public partial class morph
	{
		[Column(),        PrimaryKey, NotNull] public long   morphid      { get; set; } // integer
		[Column("morph"),             NotNull] public object morph_Column { get; set; } // varchar
	}

	[Table("morphmaps")]
	public partial class morphmap
	{
		[PrimaryKey(2), NotNull] public long   wordid  { get; set; } // integer
		[PrimaryKey(1), NotNull] public object pos     { get; set; } // character 
		[PrimaryKey(0), NotNull] public long   morphid { get; set; } // integer
	}

	[Table("pbargs")]
	public partial class pbarg
	{
		[PrimaryKey, NotNull    ] public long   argid     { get; set; } // integer
		[Column,     NotNull    ] public long   exampleid { get; set; } // integer
		[Column,        Nullable] public string arg       { get; set; } // text(max)
		[Column,        Nullable] public object narg      { get; set; } // varchar 
		[Column,        Nullable] public long?  func      { get; set; } // integer
	}

	[Table("pbargns")]
	public partial class pbargn
	{
		[PrimaryKey, NotNull    ] public object narg      { get; set; } // varchar 
		[Column,        Nullable] public object nargdescr { get; set; } // varchar
	}

	[Table("pbaspects")]
	public partial class pbaspect
	{
		[PrimaryKey, NotNull] public long   aspect     { get; set; } // integer
		[Column,     NotNull] public object aspectname { get; set; } // varchar
	}

	[Table("pbexamples")]
	public partial class pbexample
	{
		[PrimaryKey, NotNull    ] public long   exampleid   { get; set; } // integer
		[Column,     NotNull    ] public long   rolesetid   { get; set; } // integer
		[Column,     NotNull    ] public object examplename { get; set; } // varchar 
		[Column,        Nullable] public string text        { get; set; } // text(max)
		[Column,        Nullable] public long?  aspect      { get; set; } // integer
		[Column,        Nullable] public long?  form        { get; set; } // integer
		[Column,        Nullable] public long?  tense       { get; set; } // integer
		[Column,        Nullable] public long?  voice       { get; set; } // integer
		[Column,        Nullable] public long?  person      { get; set; } // integer
	}

	[Table("pbforms")]
	public partial class pbform
	{
		[PrimaryKey, NotNull] public long   form     { get; set; } // integer
		[Column,     NotNull] public object formname { get; set; } // varchar
	}

	[Table("pbfuncs")]
	public partial class pbfunc
	{
		[PrimaryKey, NotNull    ] public long   func      { get; set; } // integer
		[Column,     NotNull    ] public object funcname  { get; set; } // varchar 
		[Column,        Nullable] public object funcdescr { get; set; } // varchar
	}

	[Table("pbpersons")]
	public partial class pbperson
	{
		[PrimaryKey, NotNull] public long   person     { get; set; } // integer
		[Column,     NotNull] public object personname { get; set; } // varchar
	}

	[Table("pbrels")]
	public partial class pbrel
	{
		[PrimaryKey, NotNull    ] public long   relid     { get; set; } // integer
		[Column,     NotNull    ] public long   exampleid { get; set; } // integer
		[Column,     NotNull    ] public object rel       { get; set; } // varchar 
		[Column,        Nullable] public long?  func      { get; set; } // integer
	}

	[Table("pbroles")]
	public partial class pbrole
	{
		[PrimaryKey, NotNull    ] public long   roleid    { get; set; } // integer
		[Column,     NotNull    ] public long   rolesetid { get; set; } // integer
		[Column,     NotNull    ] public object narg      { get; set; } // varchar 
		[Column,        Nullable] public long?  func      { get; set; } // integer
		[Column,        Nullable] public long?  theta     { get; set; } // integer
		[Column,     NotNull    ] public object roledescr { get; set; } // varchar
	}

	[Table("pbrolesets")]
	public partial class pbroleset
	{
		[PrimaryKey, NotNull    ] public long   rolesetid    { get; set; } // integer
		[Column,     NotNull    ] public object rolesethead  { get; set; } // varchar 
		[Column,     NotNull    ] public object rolesetname  { get; set; } // varchar 
		[Column,     NotNull    ] public object rolesetdescr { get; set; } // varchar 
		[Column,        Nullable] public long?  pbwordid     { get; set; } // integer
	}

	[Table("pbtenses")]
	public partial class pbtens
	{
		[PrimaryKey, NotNull] public long   tense     { get; set; } // integer
		[Column,     NotNull] public object tensename { get; set; } // varchar
	}

	[Table("pbvnmaps")]
	public partial class pbvnmap
	{
		[PrimaryKey(0), NotNull] public long rolesetid { get; set; } // integer
		[PrimaryKey(1), NotNull] public long roleid    { get; set; } // integer
		[PrimaryKey(2), NotNull] public long vnclassid { get; set; } // integer
		[PrimaryKey(3), NotNull] public long vnroleid  { get; set; } // integer
	}

	[Table("pbvnthetas")]
	public partial class pbvntheta
	{
		[PrimaryKey, NotNull] public long   theta     { get; set; } // integer
		[Column,     NotNull] public object thetaname { get; set; } // varchar
	}

	[Table("pbvoices")]
	public partial class pbvoice
	{
		[PrimaryKey, NotNull] public long   voice     { get; set; } // integer
		[Column,     NotNull] public object voicename { get; set; } // varchar
	}

	[Table("pbwords")]
	public partial class pbword
	{
		[PrimaryKey, NotNull    ] public long   pbwordid { get; set; } // integer
		[Column,        Nullable] public long?  wordid   { get; set; } // integer
		[Column,        Nullable] public string lemma    { get; set; } // varchar(80)
	}

	[Table("postypes")]
	public partial class postype
	{
		[PrimaryKey, NotNull] public object pos     { get; set; } // character 
		[Column,     NotNull] public object posname { get; set; } // varchar
	}

	[Table("predicatematrix")]
	public partial class predicatematrix
	{
		[PrimaryKey, NotNull    ] public long   pmroleid    { get; set; } // integer
		[Column,        Nullable] public long?  wordid      { get; set; } // integer
		[Column,        Nullable] public long?  synsetid    { get; set; } // integer
		[Column,        Nullable] public string lemma       { get; set; } // varchar(33)
		[Column,        Nullable] public long?  vnwordid    { get; set; } // integer
		[Column,        Nullable] public long?  vnclassid   { get; set; } // integer
		[Column,        Nullable] public long?  vnroleid    { get; set; } // integer
		[Column,        Nullable] public long?  pbwordid    { get; set; } // integer
		[Column,        Nullable] public long?  pbrolesetid { get; set; } // integer
		[Column,        Nullable] public long?  pbroleid    { get; set; } // integer
		[Column,        Nullable] public long?  fnwordid    { get; set; } // integer
		[Column,        Nullable] public long?  fnluid      { get; set; } // integer
		[Column,        Nullable] public long?  fnframeid   { get; set; } // integer
		[Column,        Nullable] public long?  fnfeid      { get; set; } // integer
		[Column,        Nullable] public long?  sumoid      { get; set; } // integer
		[Column,        Nullable] public long?  wsource     { get; set; } // integer
		[Column,        Nullable] public long?  sources     { get; set; } // integer
	}

	[Table("samples")]
	public partial class sample
	{
		[Column(),         PrimaryKey(0), NotNull] public long   synsetid      { get; set; } // integer
		[Column(),         PrimaryKey(1), NotNull] public long   sampleid      { get; set; } // integer
		[Column("sample"),                NotNull] public string sample_Column { get; set; } // text(max)
	}

	[Table("semlinks")]
	public partial class semlink
	{
		[PrimaryKey(0), NotNull] public long synset1id { get; set; } // integer
		[PrimaryKey(1), NotNull] public long synset2id { get; set; } // integer
		[PrimaryKey(2), NotNull] public long linkid    { get; set; } // integer
	}

	[Table("senses")]
	public partial class sens
	{
		[PrimaryKey(0), NotNull    ] public long   wordid      { get; set; } // integer
		[Column,           Nullable] public long?  casedwordid { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long   synsetid    { get; set; } // integer
		[Column,           Nullable] public long?  senseid     { get; set; } // integer
		[Column,        NotNull    ] public long   sensenum    { get; set; } // integer
		[Column,        NotNull    ] public long   lexid       { get; set; } // integer
		[Column,           Nullable] public long?  tagcount    { get; set; } // integer
		[Column,           Nullable] public object sensekey    { get; set; } // varchar
	}

	[Table("sensemaps2021")]
	public partial class sensemaps2021
	{
		[PrimaryKey(0), NotNull] public long   wordid      { get; set; } // integer
		[PrimaryKey(1), NotNull] public long   synsetid    { get; set; } // integer
		[PrimaryKey(2), NotNull] public long   srcsynsetid { get; set; } // integer
		[PrimaryKey(3), NotNull] public double quality     { get; set; } // float
	}

	[Table("sensemaps2130")]
	public partial class sensemaps2130
	{
		[PrimaryKey(0), NotNull] public long   wordid      { get; set; } // integer
		[PrimaryKey(1), NotNull] public long   synsetid    { get; set; } // integer
		[PrimaryKey(2), NotNull] public long   srcsynsetid { get; set; } // integer
		[PrimaryKey(3), NotNull] public double quality     { get; set; } // float
	}

	[Table("sensemaps3031")]
	public partial class sensemaps3031
	{
		[PrimaryKey(0), NotNull] public long   wordid      { get; set; } // integer
		[PrimaryKey(1), NotNull] public long   synsetid    { get; set; } // integer
		[PrimaryKey(2), NotNull] public long   srcsynsetid { get; set; } // integer
		[PrimaryKey(3), NotNull] public double quality     { get; set; } // float
	}

	[Table("senses20")]
	public partial class senses20
	{
		[PrimaryKey(0), NotNull    ] public long   wordid   { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long   synsetid { get; set; } // integer
		[Column,        NotNull    ] public object pos      { get; set; } // character 
		[Column,           Nullable] public long?  senseid  { get; set; } // integer
		[Column,        NotNull    ] public long   sensenum { get; set; } // integer
		[Column,           Nullable] public object sensekey { get; set; } // varchar
	}

	[Table("senses21")]
	public partial class senses21
	{
		[PrimaryKey(0), NotNull    ] public long   wordid   { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long   synsetid { get; set; } // integer
		[Column,        NotNull    ] public object pos      { get; set; } // character 
		[Column,           Nullable] public long?  senseid  { get; set; } // integer
		[Column,        NotNull    ] public long   sensenum { get; set; } // integer
		[Column,           Nullable] public object sensekey { get; set; } // varchar
	}

	[Table("senses30")]
	public partial class senses30
	{
		[PrimaryKey(0), NotNull    ] public long   wordid   { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long   synsetid { get; set; } // integer
		[Column,        NotNull    ] public object pos      { get; set; } // character 
		[Column,           Nullable] public long?  senseid  { get; set; } // integer
		[Column,        NotNull    ] public long   sensenum { get; set; } // integer
		[Column,           Nullable] public object sensekey { get; set; } // varchar
	}

	[Table("sumofiles")]
	public partial class sumofile
	{
		[Column(),           PrimaryKey,  NotNull] public long   sumofileid      { get; set; } // integer
		[Column("sumofile"),              NotNull] public object sumofile_Column { get; set; } // varchar 
		[Column(),              Nullable         ] public object sumoversion     { get; set; } // varchar 
		[Column(),              Nullable         ] public long?  sumodate        { get; set; } // integer
	}

	[Table("sumoformulas")]
	public partial class sumoformula
	{
		[PrimaryKey, NotNull] public long   formulaid  { get; set; } // integer
		[Column,     NotNull] public string formula    { get; set; } // text(max)
		[Column,     NotNull] public long   sumofileid { get; set; } // integer
	}

	[Table("sumomaps")]
	public partial class sumomap
	{
		[PrimaryKey, NotNull] public long   synsetid  { get; set; } // integer
		[Column,     NotNull] public long   sumoid    { get; set; } // integer
		[Column,     NotNull] public object sumownrel { get; set; } // character
	}

	[Table("sumoparsemaps")]
	public partial class sumoparsemap
	{
		[PrimaryKey, NotNull    ] public long   mapid         { get; set; } // integer
		[Column,     NotNull    ] public long   formulaid     { get; set; } // integer
		[Column,     NotNull    ] public long   sumoid        { get; set; } // integer
		[Column,     NotNull    ] public object sumoparsetype { get; set; } // character 
		[Column,        Nullable] public long?  argnum        { get; set; } // integer
	}

	[Table("sumoterms")]
	public partial class sumoterm
	{
		[Column(),           PrimaryKey, NotNull] public long   sumoid          { get; set; } // integer
		[Column("sumoterm"),             NotNull] public object sumoterm_Column { get; set; } // varchar
	}

	[Table("sumotermattrs")]
	public partial class sumotermattr
	{
		[PrimaryKey(0), NotNull] public long   sumoid   { get; set; } // integer
		[PrimaryKey(1), NotNull] public object sumoattr { get; set; } // varchar
	}

	[Table("synsets")]
	public partial class synset
	{
		[PrimaryKey, NotNull    ] public long   synsetid    { get; set; } // integer
		[Column,     NotNull    ] public object pos         { get; set; } // character 
		[Column,     NotNull    ] public long   lexdomainid { get; set; } // integer
		[Column,        Nullable] public string definition  { get; set; } // text(max)
	}

	[Table("synsetmaps2031")]
	public partial class synsetmaps2031
	{
		[PrimaryKey(0), NotNull] public long   synsetid    { get; set; } // integer
		[PrimaryKey(1), NotNull] public long   srcsynsetid { get; set; } // integer
		[PrimaryKey(2), NotNull] public double quality     { get; set; } // float
	}

	[Table("synsetmaps2131")]
	public partial class synsetmaps2131
	{
		[PrimaryKey(0), NotNull] public long   synsetid    { get; set; } // integer
		[PrimaryKey(1), NotNull] public long   srcsynsetid { get; set; } // integer
		[PrimaryKey(2), NotNull] public double quality     { get; set; } // float
	}

	[Table("synsetmaps3031")]
	public partial class synsetmaps3031
	{
		[PrimaryKey(0), NotNull] public long   synsetid    { get; set; } // integer
		[PrimaryKey(1), NotNull] public long   srcsynsetid { get; set; } // integer
		[PrimaryKey(2), NotNull] public double quality     { get; set; } // float
	}

	[Table("vframes")]
	public partial class vframe
	{
		[PrimaryKey, NotNull    ] public long   frameid { get; set; } // integer
		[Column,        Nullable] public object frame   { get; set; } // varchar
	}

	[Table("vframemaps")]
	public partial class vframemap
	{
		[PrimaryKey(0), NotNull] public long synsetid { get; set; } // integer
		[PrimaryKey(1), NotNull] public long wordid   { get; set; } // integer
		[PrimaryKey(2), NotNull] public long frameid  { get; set; } // integer
	}

	[Table("vframesentences")]
	public partial class vframesentence
	{
		[PrimaryKey, NotNull    ] public long   sentenceid { get; set; } // integer
		[Column,        Nullable] public string sentence   { get; set; } // text(max)
	}

	[Table("vframesentencemaps")]
	public partial class vframesentencemap
	{
		[PrimaryKey(0), NotNull] public long synsetid   { get; set; } // integer
		[PrimaryKey(1), NotNull] public long wordid     { get; set; } // integer
		[PrimaryKey(2), NotNull] public long sentenceid { get; set; } // integer
	}

	[Table("vnclasses")]
	public partial class vnclass
	{
		[Column(),        PrimaryKey, NotNull] public long   classid  { get; set; } // integer
		[Column("class"),             NotNull] public object @class   { get; set; } // varchar 
		[Column(),                    NotNull] public object classtag { get; set; } // varchar
	}

	[Table("vnclassmembers")]
	public partial class vnclassmember
	{
		[PrimaryKey(0), NotNull] public long classid  { get; set; } // integer
		[PrimaryKey(1), NotNull] public long vnwordid { get; set; } // integer
	}

	[Table("vnclassmembersenses")]
	public partial class vnclassmembersens
	{
		[PrimaryKey(0), NotNull    ] public long   classid  { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long   vnwordid { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public long   sensenum { get; set; } // integer
		[Column,           Nullable] public long?  synsetid { get; set; } // integer
		[Column,           Nullable] public object sensekey { get; set; } // varchar 
		[Column,        NotNull    ] public double quality  { get; set; } // float
	}

	[Table("vnexamples")]
	public partial class vnexample
	{
		[PrimaryKey, NotNull] public long   exampleid { get; set; } // integer
		[Column,     NotNull] public object example   { get; set; } // varchar
	}

	[Table("vnexamplemaps")]
	public partial class vnexamplemap
	{
		[PrimaryKey(0), NotNull] public long frameid   { get; set; } // integer
		[PrimaryKey(1), NotNull] public long exampleid { get; set; } // integer
	}

	[Table("vnframes")]
	public partial class vnframe
	{
		[PrimaryKey, NotNull    ] public long   frameid     { get; set; } // integer
		[Column,        Nullable] public object number      { get; set; } // varchar 
		[Column,        Nullable] public object xtag        { get; set; } // varchar 
		[Column,     NotNull    ] public long   nameid      { get; set; } // integer
		[Column,     NotNull    ] public long   subnameid   { get; set; } // integer
		[Column,     NotNull    ] public long   syntaxid    { get; set; } // integer
		[Column,     NotNull    ] public long   semanticsid { get; set; } // integer
	}

	[Table("vnframemaps")]
	public partial class vnframemap
	{
		[PrimaryKey, NotNull] public long framemapid { get; set; } // integer
		[Column,     NotNull] public long classid    { get; set; } // integer
		[Column,     NotNull] public long frameid    { get; set; } // integer
	}

	[Table("vnframenames")]
	public partial class vnframename
	{
		[PrimaryKey, NotNull] public long   nameid    { get; set; } // integer
		[Column,     NotNull] public object framename { get; set; } // varchar
	}

	[Table("vnframesubnames")]
	public partial class vnframesubname
	{
		[PrimaryKey, NotNull] public long   subnameid    { get; set; } // integer
		[Column,     NotNull] public object framesubname { get; set; } // varchar
	}

	[Table("vngroupings")]
	public partial class vngrouping
	{
		[PrimaryKey, NotNull] public long   groupingid { get; set; } // integer
		[Column,     NotNull] public object grouping   { get; set; } // varchar
	}

	[Table("vngroupingmaps")]
	public partial class vngroupingmap
	{
		[PrimaryKey, NotNull] public long groupingmapid { get; set; } // integer
		[Column,     NotNull] public long classid       { get; set; } // integer
		[Column,     NotNull] public long vnwordid      { get; set; } // integer
		[Column,     NotNull] public long groupingid    { get; set; } // integer
	}

	[Table("vnpredicates")]
	public partial class vnpredicate
	{
		[PrimaryKey, NotNull] public long   predid { get; set; } // integer
		[Column,     NotNull] public object pred   { get; set; } // varchar
	}

	[Table("vnpredicatemaps")]
	public partial class vnpredicatemap
	{
		[PrimaryKey(0), NotNull] public long semanticsid { get; set; } // integer
		[PrimaryKey(1), NotNull] public long predid      { get; set; } // integer
	}

	[Table("vnrestrs")]
	public partial class vnrestr
	{
		[PrimaryKey, NotNull] public long   restrsid { get; set; } // integer
		[Column,     NotNull] public string restrs   { get; set; } // text(max)
		[Column,     NotNull] public bool   issyn    { get; set; } // boolean
	}

	[Table("vnrestrtypes")]
	public partial class vnrestrtype
	{
		[PrimaryKey, NotNull] public long   restrid  { get; set; } // integer
		[Column,     NotNull] public object restrval { get; set; } // varchar 
		[Column,     NotNull] public object restr    { get; set; } // varchar 
		[Column,     NotNull] public bool   issyn    { get; set; } // boolean
	}

	[Table("vnroles")]
	public partial class vnrole
	{
		[PrimaryKey, NotNull    ] public long  roleid     { get; set; } // integer
		[Column,     NotNull    ] public long  roletypeid { get; set; } // integer
		[Column,        Nullable] public long? restrsid   { get; set; } // integer
	}

	[Table("vnrolemaps")]
	public partial class vnrolemap
	{
		[PrimaryKey, NotNull] public long rolemapid { get; set; } // integer
		[Column,     NotNull] public long roleid    { get; set; } // integer
		[Column,     NotNull] public long classid   { get; set; } // integer
	}

	[Table("vnroletypes")]
	public partial class vnroletype
	{
		[PrimaryKey, NotNull] public long   roletypeid { get; set; } // integer
		[Column,     NotNull] public object roletype   { get; set; } // varchar
	}

	[Table("vnsemantics")]
	public partial class vnsemantic
	{
		[PrimaryKey, NotNull] public long   semanticsid { get; set; } // integer
		[Column,     NotNull] public string semantics   { get; set; } // text(max)
	}

	[Table("vnsyntaxes")]
	public partial class vnsyntax
	{
		[PrimaryKey, NotNull] public long   syntaxid { get; set; } // integer
		[Column,     NotNull] public string syntax   { get; set; } // text(max)
	}

	[Table("vnwords")]
	public partial class vnword
	{
		[PrimaryKey, NotNull    ] public long   vnwordid { get; set; } // integer
		[Column,        Nullable] public long?  wordid   { get; set; } // integer
		[Column,        Nullable] public string lemma    { get; set; } // varchar(80)
	}

	[Table("words")]
	public partial class word
	{
		[PrimaryKey, NotNull] public long   wordid { get; set; } // integer
		[Column,     NotNull] public object lemma  { get; set; } // varchar
	}

	[Table("xwnparselfts")]
	public partial class xwnparselft
	{
		[Column, NotNull    ] public long   synsetid     { get; set; } // integer
		[Column, NotNull    ] public string parse        { get; set; } // text(max)
		[Column, NotNull    ] public string lft          { get; set; } // text(max)
		[Column,    Nullable] public long?  parsequality { get; set; } // integer
		[Column,    Nullable] public long?  lftquality   { get; set; } // integer
	}

	[Table("xwnwsds")]
	public partial class xwnwsd
	{
		[Column, NotNull    ] public long   synsetid { get; set; } // integer
		[Column, NotNull    ] public string wsd      { get; set; } // text(max)
		[Column,    Nullable] public string text     { get; set; } // text(max)
	}

	public static partial class TableExtensions
	{
		public static adjposition Find(this ITable<adjposition> table, long synsetid, long wordid)
		{
			return table.FirstOrDefault(t =>
				t.synsetid == synsetid &&
				t.wordid   == wordid);
		}

		public static adjpositiontype Find(this ITable<adjpositiontype> table, object position)
		{
			return table.FirstOrDefault(t =>
				t.position == position);
		}

		public static bnc Find(this ITable<bnc> table, long wordid, object pos)
		{
			return table.FirstOrDefault(t =>
				t.wordid == wordid &&
				t.pos    == pos);
		}

		public static bncconvtask Find(this ITable<bncconvtask> table, long wordid, object pos)
		{
			return table.FirstOrDefault(t =>
				t.wordid == wordid &&
				t.pos    == pos);
		}

		public static bncimaginf Find(this ITable<bncimaginf> table, long wordid, object pos)
		{
			return table.FirstOrDefault(t =>
				t.wordid == wordid &&
				t.pos    == pos);
		}

		public static bncspwr Find(this ITable<bncspwr> table, long wordid, object pos)
		{
			return table.FirstOrDefault(t =>
				t.wordid == wordid &&
				t.pos    == pos);
		}

		public static casedword Find(this ITable<casedword> table, long casedwordid)
		{
			return table.FirstOrDefault(t =>
				t.casedwordid == casedwordid);
		}

		public static fnannoset Find(this ITable<fnannoset> table, long annosetid)
		{
			return table.FirstOrDefault(t =>
				t.annosetid == annosetid);
		}

		public static fncoretype Find(this ITable<fncoretype> table, long coretypeid)
		{
			return table.FirstOrDefault(t =>
				t.coretypeid == coretypeid);
		}

		public static fncorpus Find(this ITable<fncorpus> table, long corpusid)
		{
			return table.FirstOrDefault(t =>
				t.corpusid == corpusid);
		}

		public static fncxn Find(this ITable<fncxn> table, long cxnid)
		{
			return table.FirstOrDefault(t =>
				t.cxnid == cxnid);
		}

		public static fndocument Find(this ITable<fndocument> table, long documentid)
		{
			return table.FirstOrDefault(t =>
				t.documentid == documentid);
		}

		public static fnfe Find(this ITable<fnfe> table, long feid)
		{
			return table.FirstOrDefault(t =>
				t.feid == feid);
		}

		public static fnfegrouprealization Find(this ITable<fnfegrouprealization> table, long fegrid)
		{
			return table.FirstOrDefault(t =>
				t.fegrid == fegrid);
		}

		public static fnfegrouprealizations_fes Find(this ITable<fnfegrouprealizations_fes> table, long rfeid)
		{
			return table.FirstOrDefault(t =>
				t.rfeid == rfeid);
		}

		public static fnferealization Find(this ITable<fnferealization> table, long ferid)
		{
			return table.FirstOrDefault(t =>
				t.ferid == ferid);
		}

		public static fnfes_excluded Find(this ITable<fnfes_excluded> table, long feid, long fe2id)
		{
			return table.FirstOrDefault(t =>
				t.feid  == feid &&
				t.fe2id == fe2id);
		}

		public static fnfes_required Find(this ITable<fnfes_required> table, long feid, long fe2id)
		{
			return table.FirstOrDefault(t =>
				t.feid  == feid &&
				t.fe2id == fe2id);
		}

		public static fnfes_semtypes Find(this ITable<fnfes_semtypes> table, long feid, long semtypeid)
		{
			return table.FirstOrDefault(t =>
				t.feid      == feid &&
				t.semtypeid == semtypeid);
		}

		public static fnfetype Find(this ITable<fnfetype> table, long fetypeid)
		{
			return table.FirstOrDefault(t =>
				t.fetypeid == fetypeid);
		}

		public static fnframe Find(this ITable<fnframe> table, long frameid)
		{
			return table.FirstOrDefault(t =>
				t.frameid == frameid);
		}

		public static fnframerelation Find(this ITable<fnframerelation> table, long relationid)
		{
			return table.FirstOrDefault(t =>
				t.relationid == relationid);
		}

		public static fnframes_semtypes Find(this ITable<fnframes_semtypes> table, long frameid, long semtypeid)
		{
			return table.FirstOrDefault(t =>
				t.frameid   == frameid &&
				t.semtypeid == semtypeid);
		}

		public static fngftype Find(this ITable<fngftype> table, long gfid)
		{
			return table.FirstOrDefault(t =>
				t.gfid == gfid);
		}

		public static fngovernor Find(this ITable<fngovernor> table, long governorid)
		{
			return table.FirstOrDefault(t =>
				t.governorid == governorid);
		}

		public static fngovernors_annosets Find(this ITable<fngovernors_annosets> table, long governorid, long annosetid)
		{
			return table.FirstOrDefault(t =>
				t.governorid == governorid &&
				t.annosetid  == annosetid);
		}

		public static fnlabel Find(this ITable<fnlabel> table, long labelid)
		{
			return table.FirstOrDefault(t =>
				t.labelid == labelid);
		}

		public static fnlabelitype Find(this ITable<fnlabelitype> table, long labelitypeid)
		{
			return table.FirstOrDefault(t =>
				t.labelitypeid == labelitypeid);
		}

		public static fnlabeltype Find(this ITable<fnlabeltype> table, long labeltypeid)
		{
			return table.FirstOrDefault(t =>
				t.labeltypeid == labeltypeid);
		}

		public static fnlayer Find(this ITable<fnlayer> table, long layerid)
		{
			return table.FirstOrDefault(t =>
				t.layerid == layerid);
		}

		public static fnlayertype Find(this ITable<fnlayertype> table, long layertypeid)
		{
			return table.FirstOrDefault(t =>
				t.layertypeid == layertypeid);
		}

		public static fnlexeme Find(this ITable<fnlexeme> table, long lexemeid)
		{
			return table.FirstOrDefault(t =>
				t.lexemeid == lexemeid);
		}

		public static fnlexunit Find(this ITable<fnlexunit> table, long luid)
		{
			return table.FirstOrDefault(t =>
				t.luid == luid);
		}

		public static fnlexunits_governors Find(this ITable<fnlexunits_governors> table, long luid, long governorid)
		{
			return table.FirstOrDefault(t =>
				t.luid       == luid &&
				t.governorid == governorid);
		}

		public static fnlexunits_semtypes Find(this ITable<fnlexunits_semtypes> table, long luid, long semtypeid)
		{
			return table.FirstOrDefault(t =>
				t.luid      == luid &&
				t.semtypeid == semtypeid);
		}

		public static fnpattern Find(this ITable<fnpattern> table, long patternid)
		{
			return table.FirstOrDefault(t =>
				t.patternid == patternid);
		}

		public static fnpatterns_annosets Find(this ITable<fnpatterns_annosets> table, long patternid, long annosetid)
		{
			return table.FirstOrDefault(t =>
				t.patternid == patternid &&
				t.annosetid == annosetid);
		}

		public static fnpatterns_valenceunits Find(this ITable<fnpatterns_valenceunits> table, long pvid)
		{
			return table.FirstOrDefault(t =>
				t.pvid == pvid);
		}

		public static fnpos Find(this ITable<fnpos> table, long posid)
		{
			return table.FirstOrDefault(t =>
				t.posid == posid);
		}

		public static fnpttype Find(this ITable<fnpttype> table, long ptid)
		{
			return table.FirstOrDefault(t =>
				t.ptid == ptid);
		}

		public static fnsemtype Find(this ITable<fnsemtype> table, long semtypeid)
		{
			return table.FirstOrDefault(t =>
				t.semtypeid == semtypeid);
		}

		public static fnsemtypes_supers Find(this ITable<fnsemtypes_supers> table, long semtypeid, long supersemtypeid)
		{
			return table.FirstOrDefault(t =>
				t.semtypeid      == semtypeid &&
				t.supersemtypeid == supersemtypeid);
		}

		public static fnsentence Find(this ITable<fnsentence> table, long sentenceid)
		{
			return table.FirstOrDefault(t =>
				t.sentenceid == sentenceid);
		}

		public static fnstatus Find(this ITable<fnstatus> table, long statusid)
		{
			return table.FirstOrDefault(t =>
				t.statusid == statusid);
		}

		public static fnsubcorpus Find(this ITable<fnsubcorpus> table, long subcorpusid)
		{
			return table.FirstOrDefault(t =>
				t.subcorpusid == subcorpusid);
		}

		public static fnsubcorpuses_sentences Find(this ITable<fnsubcorpuses_sentences> table, long subcorpusid, long sentenceid)
		{
			return table.FirstOrDefault(t =>
				t.subcorpusid == subcorpusid &&
				t.sentenceid  == sentenceid);
		}

		public static fnvalenceunit Find(this ITable<fnvalenceunit> table, long vuid)
		{
			return table.FirstOrDefault(t =>
				t.vuid == vuid);
		}

		public static fnvalenceunits_annosets Find(this ITable<fnvalenceunits_annosets> table, long vuid, long annosetid)
		{
			return table.FirstOrDefault(t =>
				t.vuid      == vuid &&
				t.annosetid == annosetid);
		}

		public static fnword Find(this ITable<fnword> table, long fnwordid)
		{
			return table.FirstOrDefault(t =>
				t.fnwordid == fnwordid);
		}

		public static lexdomain Find(this ITable<lexdomain> table, long lexdomainid)
		{
			return table.FirstOrDefault(t =>
				t.lexdomainid == lexdomainid);
		}

		public static lexlink Find(this ITable<lexlink> table, long synset1id, long word1id, long synset2id, long word2id, long linkid)
		{
			return table.FirstOrDefault(t =>
				t.synset1id == synset1id &&
				t.word1id   == word1id   &&
				t.synset2id == synset2id &&
				t.word2id   == word2id   &&
				t.linkid    == linkid);
		}

		public static linktype Find(this ITable<linktype> table, long linkid)
		{
			return table.FirstOrDefault(t =>
				t.linkid == linkid);
		}

		public static log Find(this ITable<log> table, long id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static morph Find(this ITable<morph> table, long morphid)
		{
			return table.FirstOrDefault(t =>
				t.morphid == morphid);
		}

		public static morphmap Find(this ITable<morphmap> table, long wordid, object pos, long morphid)
		{
			return table.FirstOrDefault(t =>
				t.wordid  == wordid &&
				t.pos     == pos    &&
				t.morphid == morphid);
		}

		public static pbarg Find(this ITable<pbarg> table, long argid)
		{
			return table.FirstOrDefault(t =>
				t.argid == argid);
		}

		public static pbargn Find(this ITable<pbargn> table, object narg)
		{
			return table.FirstOrDefault(t =>
				t.narg == narg);
		}

		public static pbaspect Find(this ITable<pbaspect> table, long aspect)
		{
			return table.FirstOrDefault(t =>
				t.aspect == aspect);
		}

		public static pbexample Find(this ITable<pbexample> table, long exampleid)
		{
			return table.FirstOrDefault(t =>
				t.exampleid == exampleid);
		}

		public static pbform Find(this ITable<pbform> table, long form)
		{
			return table.FirstOrDefault(t =>
				t.form == form);
		}

		public static pbfunc Find(this ITable<pbfunc> table, long func)
		{
			return table.FirstOrDefault(t =>
				t.func == func);
		}

		public static pbperson Find(this ITable<pbperson> table, long person)
		{
			return table.FirstOrDefault(t =>
				t.person == person);
		}

		public static pbrel Find(this ITable<pbrel> table, long relid)
		{
			return table.FirstOrDefault(t =>
				t.relid == relid);
		}

		public static pbrole Find(this ITable<pbrole> table, long roleid)
		{
			return table.FirstOrDefault(t =>
				t.roleid == roleid);
		}

		public static pbroleset Find(this ITable<pbroleset> table, long rolesetid)
		{
			return table.FirstOrDefault(t =>
				t.rolesetid == rolesetid);
		}

		public static pbtens Find(this ITable<pbtens> table, long tense)
		{
			return table.FirstOrDefault(t =>
				t.tense == tense);
		}

		public static pbvnmap Find(this ITable<pbvnmap> table, long rolesetid, long roleid, long vnclassid, long vnroleid)
		{
			return table.FirstOrDefault(t =>
				t.rolesetid == rolesetid &&
				t.roleid    == roleid    &&
				t.vnclassid == vnclassid &&
				t.vnroleid  == vnroleid);
		}

		public static pbvntheta Find(this ITable<pbvntheta> table, long theta)
		{
			return table.FirstOrDefault(t =>
				t.theta == theta);
		}

		public static pbvoice Find(this ITable<pbvoice> table, long voice)
		{
			return table.FirstOrDefault(t =>
				t.voice == voice);
		}

		public static pbword Find(this ITable<pbword> table, long pbwordid)
		{
			return table.FirstOrDefault(t =>
				t.pbwordid == pbwordid);
		}

		public static postype Find(this ITable<postype> table, object pos)
		{
			return table.FirstOrDefault(t =>
				t.pos == pos);
		}

		public static predicatematrix Find(this ITable<predicatematrix> table, long pmroleid)
		{
			return table.FirstOrDefault(t =>
				t.pmroleid == pmroleid);
		}

		public static sample Find(this ITable<sample> table, long synsetid, long sampleid)
		{
			return table.FirstOrDefault(t =>
				t.synsetid == synsetid &&
				t.sampleid == sampleid);
		}

		public static semlink Find(this ITable<semlink> table, long synset1id, long synset2id, long linkid)
		{
			return table.FirstOrDefault(t =>
				t.synset1id == synset1id &&
				t.synset2id == synset2id &&
				t.linkid    == linkid);
		}

		public static sens Find(this ITable<sens> table, long wordid, long synsetid)
		{
			return table.FirstOrDefault(t =>
				t.wordid   == wordid &&
				t.synsetid == synsetid);
		}

		public static sensemaps2021 Find(this ITable<sensemaps2021> table, long wordid, long synsetid, long srcsynsetid, double quality)
		{
			return table.FirstOrDefault(t =>
				t.wordid      == wordid      &&
				t.synsetid    == synsetid    &&
				t.srcsynsetid == srcsynsetid &&
				t.quality     == quality);
		}

		public static sensemaps2130 Find(this ITable<sensemaps2130> table, long wordid, long synsetid, long srcsynsetid, double quality)
		{
			return table.FirstOrDefault(t =>
				t.wordid      == wordid      &&
				t.synsetid    == synsetid    &&
				t.srcsynsetid == srcsynsetid &&
				t.quality     == quality);
		}

		public static sensemaps3031 Find(this ITable<sensemaps3031> table, long wordid, long synsetid, long srcsynsetid, double quality)
		{
			return table.FirstOrDefault(t =>
				t.wordid      == wordid      &&
				t.synsetid    == synsetid    &&
				t.srcsynsetid == srcsynsetid &&
				t.quality     == quality);
		}

		public static senses20 Find(this ITable<senses20> table, long wordid, long synsetid)
		{
			return table.FirstOrDefault(t =>
				t.wordid   == wordid &&
				t.synsetid == synsetid);
		}

		public static senses21 Find(this ITable<senses21> table, long wordid, long synsetid)
		{
			return table.FirstOrDefault(t =>
				t.wordid   == wordid &&
				t.synsetid == synsetid);
		}

		public static senses30 Find(this ITable<senses30> table, long wordid, long synsetid)
		{
			return table.FirstOrDefault(t =>
				t.wordid   == wordid &&
				t.synsetid == synsetid);
		}

		public static sumofile Find(this ITable<sumofile> table, long sumofileid)
		{
			return table.FirstOrDefault(t =>
				t.sumofileid == sumofileid);
		}

		public static sumoformula Find(this ITable<sumoformula> table, long formulaid)
		{
			return table.FirstOrDefault(t =>
				t.formulaid == formulaid);
		}

		public static sumomap Find(this ITable<sumomap> table, long synsetid)
		{
			return table.FirstOrDefault(t =>
				t.synsetid == synsetid);
		}

		public static sumoparsemap Find(this ITable<sumoparsemap> table, long mapid)
		{
			return table.FirstOrDefault(t =>
				t.mapid == mapid);
		}

		public static sumoterm Find(this ITable<sumoterm> table, long sumoid)
		{
			return table.FirstOrDefault(t =>
				t.sumoid == sumoid);
		}

		public static sumotermattr Find(this ITable<sumotermattr> table, long sumoid, object sumoattr)
		{
			return table.FirstOrDefault(t =>
				t.sumoid   == sumoid &&
				t.sumoattr == sumoattr);
		}

		public static synset Find(this ITable<synset> table, long synsetid)
		{
			return table.FirstOrDefault(t =>
				t.synsetid == synsetid);
		}

		public static synsetmaps2031 Find(this ITable<synsetmaps2031> table, long synsetid, long srcsynsetid, double quality)
		{
			return table.FirstOrDefault(t =>
				t.synsetid    == synsetid    &&
				t.srcsynsetid == srcsynsetid &&
				t.quality     == quality);
		}

		public static synsetmaps2131 Find(this ITable<synsetmaps2131> table, long synsetid, long srcsynsetid, double quality)
		{
			return table.FirstOrDefault(t =>
				t.synsetid    == synsetid    &&
				t.srcsynsetid == srcsynsetid &&
				t.quality     == quality);
		}

		public static synsetmaps3031 Find(this ITable<synsetmaps3031> table, long synsetid, long srcsynsetid, double quality)
		{
			return table.FirstOrDefault(t =>
				t.synsetid    == synsetid    &&
				t.srcsynsetid == srcsynsetid &&
				t.quality     == quality);
		}

		public static vframe Find(this ITable<vframe> table, long frameid)
		{
			return table.FirstOrDefault(t =>
				t.frameid == frameid);
		}

		public static vframemap Find(this ITable<vframemap> table, long synsetid, long wordid, long frameid)
		{
			return table.FirstOrDefault(t =>
				t.synsetid == synsetid &&
				t.wordid   == wordid   &&
				t.frameid  == frameid);
		}

		public static vframesentence Find(this ITable<vframesentence> table, long sentenceid)
		{
			return table.FirstOrDefault(t =>
				t.sentenceid == sentenceid);
		}

		public static vframesentencemap Find(this ITable<vframesentencemap> table, long synsetid, long wordid, long sentenceid)
		{
			return table.FirstOrDefault(t =>
				t.synsetid   == synsetid &&
				t.wordid     == wordid   &&
				t.sentenceid == sentenceid);
		}

		public static vnclass Find(this ITable<vnclass> table, long classid)
		{
			return table.FirstOrDefault(t =>
				t.classid == classid);
		}

		public static vnclassmember Find(this ITable<vnclassmember> table, long classid, long vnwordid)
		{
			return table.FirstOrDefault(t =>
				t.classid  == classid &&
				t.vnwordid == vnwordid);
		}

		public static vnclassmembersens Find(this ITable<vnclassmembersens> table, long classid, long vnwordid, long sensenum)
		{
			return table.FirstOrDefault(t =>
				t.classid  == classid  &&
				t.vnwordid == vnwordid &&
				t.sensenum == sensenum);
		}

		public static vnexample Find(this ITable<vnexample> table, long exampleid)
		{
			return table.FirstOrDefault(t =>
				t.exampleid == exampleid);
		}

		public static vnexamplemap Find(this ITable<vnexamplemap> table, long frameid, long exampleid)
		{
			return table.FirstOrDefault(t =>
				t.frameid   == frameid &&
				t.exampleid == exampleid);
		}

		public static vnframe Find(this ITable<vnframe> table, long frameid)
		{
			return table.FirstOrDefault(t =>
				t.frameid == frameid);
		}

		public static vnframemap Find(this ITable<vnframemap> table, long framemapid)
		{
			return table.FirstOrDefault(t =>
				t.framemapid == framemapid);
		}

		public static vnframename Find(this ITable<vnframename> table, long nameid)
		{
			return table.FirstOrDefault(t =>
				t.nameid == nameid);
		}

		public static vnframesubname Find(this ITable<vnframesubname> table, long subnameid)
		{
			return table.FirstOrDefault(t =>
				t.subnameid == subnameid);
		}

		public static vngrouping Find(this ITable<vngrouping> table, long groupingid)
		{
			return table.FirstOrDefault(t =>
				t.groupingid == groupingid);
		}

		public static vngroupingmap Find(this ITable<vngroupingmap> table, long groupingmapid)
		{
			return table.FirstOrDefault(t =>
				t.groupingmapid == groupingmapid);
		}

		public static vnpredicate Find(this ITable<vnpredicate> table, long predid)
		{
			return table.FirstOrDefault(t =>
				t.predid == predid);
		}

		public static vnpredicatemap Find(this ITable<vnpredicatemap> table, long semanticsid, long predid)
		{
			return table.FirstOrDefault(t =>
				t.semanticsid == semanticsid &&
				t.predid      == predid);
		}

		public static vnrestr Find(this ITable<vnrestr> table, long restrsid)
		{
			return table.FirstOrDefault(t =>
				t.restrsid == restrsid);
		}

		public static vnrestrtype Find(this ITable<vnrestrtype> table, long restrid)
		{
			return table.FirstOrDefault(t =>
				t.restrid == restrid);
		}

		public static vnrole Find(this ITable<vnrole> table, long roleid)
		{
			return table.FirstOrDefault(t =>
				t.roleid == roleid);
		}

		public static vnrolemap Find(this ITable<vnrolemap> table, long rolemapid)
		{
			return table.FirstOrDefault(t =>
				t.rolemapid == rolemapid);
		}

		public static vnroletype Find(this ITable<vnroletype> table, long roletypeid)
		{
			return table.FirstOrDefault(t =>
				t.roletypeid == roletypeid);
		}

		public static vnsemantic Find(this ITable<vnsemantic> table, long semanticsid)
		{
			return table.FirstOrDefault(t =>
				t.semanticsid == semanticsid);
		}

		public static vnsyntax Find(this ITable<vnsyntax> table, long syntaxid)
		{
			return table.FirstOrDefault(t =>
				t.syntaxid == syntaxid);
		}

		public static vnword Find(this ITable<vnword> table, long vnwordid)
		{
			return table.FirstOrDefault(t =>
				t.vnwordid == vnwordid);
		}

		public static word Find(this ITable<word> table, long wordid)
		{
			return table.FirstOrDefault(t =>
				t.wordid == wordid);
		}
	}
}
